### ISSUE TITLE
Supporting bullet point lists

### ISSUE THREAD

**Issue by h4cc** [thejameskyle/spectacle-code-slide#4]
Is it possible to support

* very
* important
* bullet
* point
* lists

? :smile: 

Maybe via Markdown source files or so?

**Comment by thejameskyle** [comment]
You mean in the note?

**Comment by h4cc** [comment]
If the note is the slide body: yes, please.

**Comment by thejameskyle** [comment]
The black bar at the bottom is the note.

<img width="1036" alt="screen shot 2016-03-27 at 2 47 56 pm" src="https://cloud.githubusercontent.com/assets/952783/14068010/e8a6ef34-f42a-11e5-9db9-40b3aa88743e.png">

I assume by slide body you mean code. In which case I would say no it shouldn't support bullet point lists as that would break the code highlighter and how it splits the individual lines up

**Comment by h4cc** [comment]
Thanks for the explanation.

Most of my code presentations look like this: "text, list, code, text, code, list, code, ...".
So having a way to show text and bullet point lists between code files would make this tool more interesting for me :)

**Comment by atuttle** [comment]
@h4cc this repo is for a customized slide component with the functionality seen in the readme/demo. It's not a wholesale replacement for Spectacle. The intention is that _when you need a slide that shows code_ you can use a `CodeSlide` rather than just a `Slide`, to get the enhanced experience on your slides that have code on them. Your lists/text slides should continue to use Spectacle's `Slide` component.

**Comment by thejameskyle** [comment]
Yeah my slide deck for this kept switching between regular Slides and CodeSlides with the same code. If you jump back to the same `loc` where you left off it works well.
